# Usa un'immagine di base di Docker Hub che includa il runtime Java
FROM openjdk:11-jdk

# Imposta la directory di lavoro all'interno del container
WORKDIR /app

# Copia il JAR compilato del tuo backend nella directory del container
COPY target/nome-del-tuo-backend.jar /app/nome-del-tuo-backend.jar

# Esponi la porta su cui il tuo backend ascolterà le richieste HTTP
EXPOSE 8080

# Comando da eseguire quando il container viene avviato
CMD ["java", "-jar", "nome-del-tuo-backend.jar"]
